// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ctbgzzmcxggkbtidslya.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Ymd6em1jeGdna2J0aWRzbHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyNjU5NDEsImV4cCI6MjA0Nzg0MTk0MX0.xfKlY8265junBwXKum2ei5l1cQH92UPIQC0EbnhxWWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);